services:
  vproapp:
    build:
      context: ./Docker-files/app
    image: denisgjonmarkaj/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  
  vprodb:
    build:
      context: ./Docker-files/db
    image: denisgjonmarkaj/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=accounts
    restart: always
  
  vproweb:
    build:
      context: ./Docker-files/web
    image: denisgjonmarkaj/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    #volumes:
    # - vprowebdata:/usr/share/nginx/html/ 
    # volume non serve per nginx
    
  vprocache01:
    image: memcached
    ports: 
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports: 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
     
volumes:
  vprodbdata: {}
  vproappdata: {}


#networks:
 # vprofile-network:
#  driver: bridge
